apiVersion: v1
kind: ServiceAccount
metadata:
  name: nerv-dashboard-sa
  namespace: nerv-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nerv-dashboard-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nerv-dashboard-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nerv-dashboard-role
subjects:
  - kind: ServiceAccount
    name: nerv-dashboard-sa
    namespace: nerv-dashboard
